# Generated by Django 4.0.5 on 2022-10-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_choice',
            new_name='variation_value',
        ),
    ]
